XmacsLabs/goldfish

- README.md
- goldfish/scheme/time.scm
How to test
```
bin/goldfish -e "(begin (import (scheme time)) (current-second))"
bin/goldfish -e "(begin (import (scheme time)) (current-jiffy))"
```
> (scheme time)

- src/goldfish.cpp
- src/goldfish.hpp
```
bin/goldfish -e "(version)"
```
> Implement (version)

- goldfish/liii/os.scm
- src/goldfish.hpp
- tests/demo_chdir.scm
``chdir``: implemented ``chdir`` (change directory) function, tests are also included in tests/demo_chdir.scm
To test:
```console
xmake b goldfish
bin/goldfish -l tests/demo_chdir.scm  
```
> implement chdir in (liii os)

- Goldfish.tmu
- goldfish/liii/list.scm
- tests/goldfish/liii/list-test.scm
modified: goldfish/liii/list.scm
modified: tests/goldfish/liii/list-test.scm
修改：    goldfish/liii/list.scm
修改：    tests/goldfish/liii/list-test.scm
> flatten in (liii list)

- Goldfish.tmu
- goldfish/liii/base.scm
- goldfish/liii/list.scm
- goldfish/scheme/base.scm
- goldfish/srfi/srfi-1.scm
- tests/goldfish/liii/base-test.scm
- tests/goldfish/liii/list-test.scm
Implemented list-copy and added unit test for it
> [list-copy] Implemented list-copy and added unit test for it

- Goldfish.tmu
- goldfish/liii/base.scm
- goldfish/scheme/base.scm
- tests/goldfish/liii/base-test.scm
[symbol=?] Implemented R7RS: symbol=? and added unit test
> [symbol=?] Implemented R7RS: symbol=? and added unit test

- Goldfish.tmu
- goldfish/liii/base.scm
- goldfish/liii/string.scm
- goldfish/scheme/base.scm
- tests/goldfish/liii/base-test.scm
- tests/goldfish/scheme/char-test.scm
Implemented `string->symbol`and `symbol->string` in Section 6.5 of R7RS
> string->symbol and symbol->string in R7RS

- Goldfish.tmu
- goldfish/liii/base64.scm
bitwise-and, bitwise-ior are better than logand, logior
> Use bitwise-and, bitwise-ior in (liii base64)

- .gitignore
- Goldfish.tmu
Added a new subsection to introduce the en/decoding rule of base64
> documentation for (liii base64)

- AUTHORS
- Goldfish.tmu
Preview of https://github.com/LiiiLabs/goldfish/blob/da/cc-by/AUTHORS
> Use CC-BY for the documentation part

- Goldfish.tmu
- goldfish/liii/vector.scm
- goldfish/srfi/srfi-133.scm
- tests/goldfish/liii/vector-test.scm
- tests/goldfish/srfi/srfi-133-test.scm
Write a vector-cumulate with typed-lambda, provided some ease cases for test.
> vector-cumulate in (srfi srfi-133) and (liii vector)

- Goldfish.tmu
- goldfish/liii/vector.scm
- goldfish/srfi/srfi-133.scm
- tests/goldfish/liii/vector-test.scm
I've write the reverse-list->vector, and provide some test cases including annotations.
> reverse-list->vector finished.

- Goldfish.tmu
- goldfish/srfi/srfi-133.scm
I deleted the length 1 case, as it can be included by cdr, loop.
btw., I'm wondering if the efficiency of "if" and "cond" is nearly same? As I found it seems like in most two cases listing, we use "if".
> Improve the reverse-list->vector.

- Goldfish.tmu
- goldfish/liii/list.scm
- goldfish/srfi/srfi-1.scm
- tests/goldfish/liii/list-test.scm
修改：     Goldfish.tmu
modified   goldfish/liii/list.scm
修改：     goldfish/liii/list.scm
modified   goldfish/srfi/srfi-1.scm
修改：     goldfish/srfi/srfi-1.scm
modified   tests/goldfish/liii/list-test.scm
修改：     tests/goldfish/liii/list-test.scm
往 srfi-1 中添加了 split-at，使用 values 作为返回结果
> add split-at in (liii list) and (srfi srfi-1)

- Goldfish.tmu
- tests/goldfish/liii/base-test.scm
Add unit tests and documentation for positive? and negative?
Resolves LiiiLabs/goldfish#126
> Add unit tests and documentation for positive? and negative?

- Goldfish.tmu
- goldfish/liii/bitwise.scm
- goldfish/srfi/srfi-151.scm
- tests/goldfish/liii/base-test.scm
- tests/goldfish/liii/bitwise-test.scm
Based on srfi-151 implementation
> bitwise-orc1 and bitwise-orc2 in (liii bitwise)

- Goldfish.tmu
- goldfish/liii/bitwise.scm
- goldfish/srfi/srfi-151.scm
- tests/goldfish/liii/bitwise-test.scm
Based on SRFI151 update bitwise_andc1 and bitwise_andc2
> bitwise_andc1 and bitwise_andc2 in (liii bitwise)

- Goldfish.tmu
- tests/goldfish/liii/base-test.scm
Added unit tests and description for do:
- Verified correct iteration and return value upon termination.
- Tested handling of multiple variable bindings and updates.
- Ensured proper behavior when step expressions are omitted.
- Validated execution of side effects, such as modifying a vector.
These tests ensure compliance with R7RS standards and improve reliability of do expression handling.
> Add unit test and description for do in (liii base) #136

- Goldfish.tmu
- src/goldfish.hpp
- xmake.lua
Here is deb path:
```
build/xpack/goldfish/goldfish-linux-x86_64-v17.11.0.deb
```
> Use xmake pack to produce the deb package

- AUTHORS
- GoldfishScheme.tmu
- README.md
- README_ZH.md
New Contributor: Yancheng Li from department of mathematics at SUSTech
> New Contributor: Yancheng Li

- GoldfishScheme.tmu
- tests/goldfish/liii/base-test.scm
added documentation for define*
> added documentation for define* in (liii base)

- AUTHORS
- GoldfishScheme.tmu
很高兴介绍我们的新贡献者俞昕毅。他是南方科技大学数学系的三年级本科生，同时也是三鲤网络科技提供的软件开发教程([转码：大型项目开发入门](https://liiistem.cn/guide/tutorials/sde_tutorial.html))的学员。他完成了[在GoldfishLang.tmu中实现 rich-list%drop的任务](https://gitee.com/LiiiLabs/goldfish/pulls/130)。
I am glad to introduce our new contributor Xinyi Yu. He is a third-year undergraduate student from the department of mathematics at Southern University of Science and Technology. Xinyi is also a student in the software development tutorial provided by Liii Network ([转码：大型项目开发入门](https://liiistem.cn/guide/tutorials/sde_tutorial.html)). He finished the task of [adding rich-list%drop in Goldfish Lang.tmu](https://gitee.com/LiiiLabs/goldfish/pulls/130).
> New Contributor: Xinyi Yu at SUSTech

- GoldfishLang.tmu
- goldfish/liii/lang.scm
- tests/goldfish/liii/lang-test.scm
added concat function for rich-list class.
Note that concat is a static function.
> added rich-list@concat

- GoldfishLang.tmu
- goldfish/liii/lang.scm
- tests/goldfish/liii/lang-test.scm
revise concat function to support chaining.
> revised rich-list@concat

- GoldfishLang.tmu
- goldfish/liii/lang.scm
- tests/goldfish/liii/lang-test.scm
added rich-string%split in GoldfishLang.tmu
> added rich-string%split in GoldfishLang.tmu

- GoldfishLang.tmu
- GoldfishStandardLibrary.tmu
- goldfish/liii/lang.scm
- tests/goldfish/liii/lang-test.scm
- tests/goldfish/liii/path-test.scm
1. add rich-list%last and rich-list%last-option
2. revise several failed test
> add rich-list%last and rich-list%last-option && revise test for path%name and path%stem

- GoldfishLang.tmu
- goldfish/liii/lang.scm
Before optimization
```bash
rich-list%empty%length:	367267
```
After optimization
```bash
rich-list%empty%length:	44184
```
> perf: 8x improvement of rich-list in (liii lang)

- GoldfishStandardLibrary.tmu
- goldfish/liii/os.scm
- src/goldfish.hpp
- tests/goldfish/liii/os-test.scm
> add putenv in (liii os)

- goldfish/liii/range.scm
- liii_range.tmu
- tests/goldfish/liii/range-test.scm
add %for-each for range, supplement missing test for range%map
> add %for-each for range
